<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    function testFinally() {
        try {
            return 2;
        } catch (error) {
            return 1;
        } finally {
            return 0;
        }
    }

    var items1 = new Array(-20);    // 抛出RangeError
    var items2 = new Array(Number.MAX_VALUE);   // 抛出RangeError

    var obj = x;		// 在x并未声明的情况下抛出ReferenceError

    eval('a ++ b');     // 抛出SyntaxError

    var o = new 10;     // 抛出TypeError
    console.log('name' in true);    // 抛出TypeError
    Function.prototype.toString.call('name');   // 抛出TypeError

    try {
        someFunction();
    }catch (error){
        if (error instanceof TypeError){
            // 处理类型错误
        }else if (error instanceof ReferenceError){
            // 处理引用错误
        }else {
            // 处理其他类型错误
        }
    }

    throw 12345;
    throw 'hello';
    throw true;
    throw {name: 'JavaScript'};

    throw new Error('something bad happened');
    throw new SyntaxError("i don't like your syntax");
    throw new TypeError('what type of variable do you take me for');
    throw new RangeError('Sorry, you just do not have the range');
    throw new EvalError('that does not evaluate');
    throw new URIError('uri, is that you');
    throw new ReferenceError('you do not cite your references properly');

    function CustomError(message) {
        this.name = 'CustomError';
        this.message = message;
    }

    CustomError.prototype = new Error();

    throw new CustomError('My message');
</script>
</body>
</html>